import { parseMarkdownBlocks, type InlineSpan } from './markdownText'

/**
 * LaTeX symbol extraction for tutor lessons.
 *
 * The symbols panel is derived from the lesson text itself, never generated by
 * the model separately — that is the only way the panel can be guaranteed to
 * match what the student actually read.
 *
 * Extraction is generic (any `\command` is recognised) with a curated name
 * table layered on top for the symbols a STEM course actually uses. Unknown
 * commands are still surfaced, with a humanised name, rather than dropped.
 */

export interface ExtractedSymbol {
  /** The command itself, e.g. `\cap`. Unique within a lesson. */
  latex: string
  /** LaTeX for the panel to render, e.g. `A \cap B`. */
  displayLatex: string
  /** English fallback name; the UI prefers a translated label when it has one. */
  name: string
}

/**
 * Layout / font commands that are not mathematical symbols. Showing them would
 * clutter the panel with `\left`, `\text` and friends.
 */
const STRUCTURAL = new Set([
  'begin', 'end', 'left', 'right', 'middle', 'text', 'textrm', 'textit',
  'mathrm', 'mathbf', 'mathit', 'mathsf', 'mathtt', 'operatorname',
  'label', 'ref', 'tag', 'quad', 'qquad', 'displaystyle', 'textstyle',
  'scriptstyle', 'limits', 'nolimits', 'nonumber', 'notag', 'hspace',
  'vspace', 'hline', 'item', 'big', 'Big', 'bigg', 'Bigg', 'ensuremath',
  'mathopen', 'mathclose', 'mathbin', 'mathrel', 'mathord', 'mathpunct',
  'mathop', 'phantom', 'hphantom', 'vphantom', 'smash', 'raisebox',
])

/**
 * Commands whose single braced argument is part of how the symbol reads
 * (`\overline{Y}`), so it is kept in the display form.
 */
const SINGLE_ARGUMENT = new Set([
  'overline', 'underline', 'sqrt', 'vec', 'hat', 'bar', 'tilde', 'dot',
  'ddot', 'widehat', 'widetilde', 'mathbb', 'mathcal', 'mathfrak',
])

interface KnownSymbol {
  name: string
  /** A short, representative LaTeX expression for the panel. */
  sample: string
}

/**
 * Names for the symbols a university STEM course is likely to use. Anything
 * missing still appears in the panel via the humanised fallback.
 */
const KNOWN: Record<string, KnownSymbol> = {
  // Set theory
  cap: { name: 'Intersection', sample: 'A \\cap B' },
  cup: { name: 'Union', sample: 'A \\cup B' },
  in: { name: 'Element of', sample: 'x \\in A' },
  notin: { name: 'Not an element of', sample: 'x \\notin A' },
  subset: { name: 'Subset', sample: 'A \\subset B' },
  subseteq: { name: 'Subset or equal to', sample: 'A \\subseteq B' },
  supset: { name: 'Superset', sample: 'A \\supset B' },
  supseteq: { name: 'Superset or equal to', sample: 'A \\supseteq B' },
  emptyset: { name: 'Empty set', sample: '\\emptyset' },
  setminus: { name: 'Set difference', sample: 'A \\setminus B' },
  overline: { name: 'Complement', sample: '\\overline{A}' },
  // Calculus
  frac: { name: 'Fraction', sample: '\\frac{a}{b}' },
  sqrt: { name: 'Square root', sample: '\\sqrt{x}' },
  sum: { name: 'Summation', sample: '\\sum_{i=1}^{n} i' },
  prod: { name: 'Product', sample: '\\prod_{i=1}^{n} i' },
  int: { name: 'Integral', sample: '\\int_0^\\infty e^{-x^2} dx' },
  partial: { name: 'Partial derivative', sample: '\\partial f' },
  nabla: { name: 'Gradient / del', sample: '\\nabla f' },
  lim: { name: 'Limit', sample: '\\lim_{x \\to a} f(x)' },
  infty: { name: 'Infinity', sample: '\\infty' },
  to: { name: 'Tends to', sample: 'x \\to a' },
  // Relations and logic
  le: { name: 'Less than or equal', sample: 'x \\le y' },
  ge: { name: 'Greater than or equal', sample: 'x \\ge y' },
  neq: { name: 'Not equal', sample: 'x \\neq y' },
  approx: { name: 'Approximately equal', sample: 'x \\approx y' },
  equiv: { name: 'Equivalent', sample: 'x \\equiv y' },
  propto: { name: 'Proportional to', sample: 'y \\propto x' },
  pm: { name: 'Plus or minus', sample: '\\pm x' },
  times: { name: 'Multiplication', sample: 'a \\times b' },
  cdot: { name: 'Dot product / multiply', sample: 'a \\cdot b' },
  div: { name: 'Division', sample: 'a \\div b' },
  forall: { name: 'For all', sample: '\\forall x' },
  exists: { name: 'There exists', sample: '\\exists x' },
  neg: { name: 'Negation', sample: '\\neg P' },
  land: { name: 'Logical and', sample: 'P \\land Q' },
  lor: { name: 'Logical or', sample: 'P \\lor Q' },
  implies: { name: 'Implies', sample: 'P \\implies Q' },
  iff: { name: 'If and only if', sample: 'P \\iff Q' },
  // Linear algebra
  vec: { name: 'Vector', sample: '\\vec{v}' },
  hat: { name: 'Unit vector', sample: '\\hat{v}' },
  dot: { name: 'Time derivative', sample: '\\dot{x}' },
  mathbb: { name: 'Number set', sample: '\\mathbb{R}' },
  mathcal: { name: 'Calligraphic set', sample: '\\mathcal{L}' },
  // Greek (the common ones; the rest fall through to the humanised name)
  alpha: { name: 'Alpha', sample: '\\alpha' },
  beta: { name: 'Beta', sample: '\\beta' },
  gamma: { name: 'Gamma', sample: '\\gamma' },
  delta: { name: 'Delta', sample: '\\delta' },
  epsilon: { name: 'Epsilon', sample: '\\epsilon' },
  theta: { name: 'Theta', sample: '\\theta' },
  lambda: { name: 'Lambda', sample: '\\lambda' },
  mu: { name: 'Mu', sample: '\\mu' },
  pi: { name: 'Pi', sample: '\\pi' },
  rho: { name: 'Rho', sample: '\\rho' },
  sigma: { name: 'Sigma', sample: '\\sigma' },
  tau: { name: 'Tau', sample: '\\tau' },
  phi: { name: 'Phi', sample: '\\phi' },
  omega: { name: 'Omega', sample: '\\omega' },
  // Statistics
  bar: { name: 'Sample mean', sample: '\\bar{x}' },
  sigma_: { name: 'Standard deviation', sample: '\\sigma' },
  sim: { name: 'Distributed as', sample: 'X \\sim N(0,1)' },
}

/** `\cap` -> `cap`; used as a stable lookup key. */
export function symbolKey(latex: string): string {
  return latex.replace(/^\\/, '')
}

/** `\overline` -> `Overline` — readable when we have no curated name. */
function humanise(command: string): string {
  const spaced = command.replace(/([a-z])([A-Z])/g, '$1 $2')
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}

const COMMAND_PATTERN = /\\([a-zA-Z]+)(?:\{([^{}]*)\})?/g

/**
 * Find every LaTeX symbol used in `text`, deduplicated by command.
 *
 * `\overline{Y}` yields the command `\overline` with `{Y}` kept for display;
 * `A \cap B` yields `\cap` with the representative sample `A \cap B`.
 */
export function extractLatexSymbols(text: string): ExtractedSymbol[] {
  if (!text) return []

  const found = new Map<string, ExtractedSymbol>()
  COMMAND_PATTERN.lastIndex = 0

  for (let match = COMMAND_PATTERN.exec(text); match; match = COMMAND_PATTERN.exec(text)) {
    const command = match[1]
    if (!command || STRUCTURAL.has(command)) continue

    const latex = `\\${command}`
    if (found.has(latex)) continue

    const argument = match[2]
    const known = KNOWN[command]

    let displayLatex: string
    if (argument && SINGLE_ARGUMENT.has(command)) {
      displayLatex = `${latex}{${argument}}`
    } else if (known) {
      displayLatex = known.sample
    } else if (argument) {
      displayLatex = `${latex}{${argument}}`
    } else {
      displayLatex = latex
    }

    found.set(latex, {
      latex,
      displayLatex,
      name: known?.name ?? humanise(command),
    })
  }

  return [...found.values()]
}

/** True when a command has a curated (translatable) name. */
export function isKnownSymbol(latex: string): boolean {
  return symbolKey(latex) in KNOWN
}

/**
 * Every LaTeX fragment a lesson actually typesets, in document order.
 *
 * Only math delimited as math counts. Fenced code blocks are skipped, because a
 * backslash in sample code (`C:\Users`, `\n`, a regex) is not a mathematical
 * symbol, and bare `\commands` in prose are not treated as math either — the
 * lesson prompt requires all maths to be wrapped in `\(…\)` / `\[…\]`.
 */
export function collectMathFragments(markdown: string): string[] {
  const fragments: string[] = []
  const pushSpans = (spans: InlineSpan[]): void => {
    for (const span of spans) if (span.kind === 'math') fragments.push(span.value)
  }

  for (const block of parseMarkdownBlocks(markdown)) {
    switch (block.kind) {
      case 'math':
        fragments.push(block.value)
        break
      case 'heading':
      case 'paragraph':
      case 'quote':
        pushSpans(block.spans)
        break
      case 'list':
        for (const item of block.items) pushSpans(item)
        break
      default:
        break
    }
  }
  return fragments
}

/**
 * The symbols panel's source of truth: extract from the lesson's real maths.
 *
 * Reading through the Markdown structure (rather than scanning the raw text)
 * means code samples and prose can never leak fake symbols into the panel.
 */
export function extractSymbolsFromMarkdown(markdown: string): ExtractedSymbol[] {
  return extractLatexSymbols(collectMathFragments(markdown).join('\n'))
}
